const APP = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  APP_STAGE: 'APP_STAGE',
} as const;

const DATABASE = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

const JWT = {
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_ISSUER: 'JWT_ISSUER',
  JWT_AUDIENCES: 'JWT_AUDIENCES',
  JWT_ACCESS_TOKEN_EXPIRES_IN: 'JWT_ACCESS_TOKEN_EXPIRES_IN',
  JWT_REFRESH_TOKEN_EXPIRES_IN: 'JWT_REFRESH_TOKEN_EXPIRES_IN',
} as const;

const AWS_S3 = {
  AWS_S3_BUCKET_NAME: 'AWS_S3_BUCKET_NAME',
  AWS_S3_REGION: 'AWS_S3_REGION',
  AWS_S3_URL: 'AWS_S3_URL',
  AWS_S3_ACCESS_KEY: 'AWS_S3_ACCESS_KEY',
  AWS_S3_SECRET_KEY: 'AWS_S3_SECRET_KEY',
  AWS_S3_PRE_SIGNED_URL_EXPIRES_IN_SECOND:
    'AWS_S3_PRE_SIGNED_URL_EXPIRES_IN_SECOND',
} as const;

export const ENV_KEY = {
  ...APP,
  ...DATABASE,
  ...JWT,
  ...AWS_S3,
} as const;
